basket/urls.py
from django.urls import path, include
from . import views

app_name = 'basket'

urlpatterns = [
    path('basket/', include([
        # path('', views.basket_list, name='list'),
        path('<bookTitle>/add/', views.add_to_basket, name='add'),
        path('<bookTitle>/remove/', views.remove_from_basket, name='remove'),
        path('delete/', views.delete_basket, name='delete'),
    ])),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('treasure.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include('basket.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

treasure/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('shop', views.shop, name="shop"),
    path('contact', views.contact, name="contact"),
    path('details/<str:id>', views.bookDetails, name="bookDetails"),
    path("category/<str:name>", views.category, name="category"),
    path('search', views.search, name="search"),
    path('register/', views.register, name="register"),
    path('cart', views.cart, name="cart"),
    path('checkout', views.checkout, name="checkout"),
    path('news', views.news, name="news"),
    path('newsDetails/<str:title>', views.newsDetails, name="newsDetails"),
    path('compare', views.compare, name="compare"),
    path('wishlist', views.wishlist, name="wishlist"),
    path('account', views.account, name="account"),
    path('order_complete', views.order_complete, name="order_complete"),
    path('faq', views.faq, name="faq"),



    # path("post/<str:id>", views.post, name="post"),
]

treasure/models.py
from django.db import models
from django.contrib.auth.models import User

class UserDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50,  blank=True, verbose_name="Ім'я")
    lastname = models.CharField(max_length=75, blank=True, verbose_name="Прізвище")
    bankCard = models.CharField(max_length=75, blank=True, verbose_name="Номер банківської картки")
    address = models.CharField(max_length=100, blank=True, verbose_name="Місто")
    city = models.CharField(max_length=75, blank=True, verbose_name="Місто")
    region = models.CharField(max_length=75, blank=True, verbose_name="Область")
    zip = models.CharField(max_length=10, blank=True, verbose_name="Поштовий Індекс")
    phone = models.CharField(max_length=20, blank=True, verbose_name="Телефон")
    avatar = models.ImageField(upload_to='avatars', default="avatars/author-logo.png",  blank=True, verbose_name="Avatar")

    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name = "Деталі користувача"
        verbose_name_plural = "Деталі користувача"

class Categories(models.Model):
    category = models.CharField(max_length=20, unique=True, verbose_name="Категорія")
    def __str__(self):
        return self.category

    class Meta:     # создание перевода
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class News(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    content = models.TextField()
    published_date = models.DateTimeField(auto_created=True, verbose_name="дата і час")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="користувач")
    image = models.ImageField(upload_to='uploads', blank=True)


    def __str__(self): # замена вывода на админке
        return self.title

    class Meta:     # создание перевода
        verbose_name = "Новина"
        verbose_name_plural = "Новини"


class Books(models.Model):
    title = models.CharField(max_length=75, verbose_name="Назва", unique=True)
    author = models.CharField(max_length=75, verbose_name="Автор")
    description = models.TextField(max_length=1000, verbose_name="Опис")
    additionalInfo = models.TextField(max_length=500, verbose_name="Додаткова інформація")
    image = models.ImageField(upload_to='uploads', verbose_name="Обкладинка")
    image2 = models.ImageField(upload_to='uploads', blank=True, verbose_name="Зображення 1")
    image3 = models.ImageField(upload_to='uploads', blank=True, verbose_name="Зображення 2")
    image4 = models.ImageField(upload_to='uploads', blank=True, verbose_name="Зображення 3")
    image5 = models.ImageField(upload_to='uploads', blank=True, verbose_name="Зображення 4")
    fk_category = models.ManyToManyField(Categories, blank=True, related_name="books")
    price = models.FloatField(verbose_name="Ціна")
    pages = models.SmallIntegerField(verbose_name="Сторінок")
    ISBN = models.CharField(max_length=25, verbose_name="ISBN")
    quantity = models.IntegerField(verbose_name="Кількість на складі")
    rating = models.CharField(max_length=50, verbose_name="Рейтинг")
    size = models.CharField(max_length=20, verbose_name="Розміри")

    def __str__(self): # замена вывода на админке
        return self.title
    class Meta:     # создание перевода
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

class Discount(models.Model):
    name = models.CharField(max_length=50, verbose_name="Назва")
    description = models.TextField(max_length=300, verbose_name="Опис")
    discount = models.SmallIntegerField(default=0, verbose_name="Знижка")

    def __str__(self): # замена вывода на админке
        return self.name

    class Meta:     # создание перевода
        verbose_name = "Знижка"
        verbose_name_plural = "Знижки"


class Comments(models.Model):
    comment = models.TextField(verbose_name="Коментар")
    publish_date = models.DateTimeField(auto_created=True, verbose_name="Дата і час")
    posted = models.ForeignKey(Books, on_delete=models.CASCADE, verbose_name="Пост")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Користувач")
    name = models.CharField(max_length=50, verbose_name="Імя'")
    rating = models.CharField(max_length=50, verbose_name="Рейтинг")
    email = models.EmailField(verbose_name="Email")
    def __str__(self): # замена вывода на админке
        return f"{self.name} к посту '{self.posted.title}' написал: {self.comment[:10]}..."
    class Meta:     # создание перевода
        verbose_name = "Коментар"
        verbose_name_plural = "Коментарі"


class Orders(models.Model):
    firstname = models.CharField(max_length=50, verbose_name="Ім'я")
    lastname = models.CharField(max_length=75, verbose_name="Прізвище")
    bankCard = models.CharField(max_length=75, blank=True, verbose_name="Номер банківської картки")
    email = models.EmailField(max_length=75, verbose_name="email")
    address = models.CharField(max_length=100, verbose_name="Адреса")
    city = models.CharField(max_length=75, verbose_name="Місто")
    region = models.CharField(max_length=75, verbose_name="Область")
    zip = models.CharField(max_length=10, verbose_name="Поштовий Індекс")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    notes = models.TextField(blank=True, verbose_name="Коментар")
    orderedBook = models.ManyToManyField(Books, related_name="books")
    user_id = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, verbose_name="користувач")

    def __str__(self):
        return self.email
    class Meta:
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

treasure/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .models import Books, News, Comments, Categories, Orders, User, UserDetails
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.contrib import messages
# from django.views.generic import ListView

def get_categories():
    all= Categories.objects.all().order_by('category')
    return {'catList': all[:8], 'extendList': all[9:]}


def check_password(username, password):
    try:
        user = User.objects.get(username=username)
        return user.check_password(password)
    except User.DoesNotExist:
        return False

def index(request):
    books = Books.objects.all().order_by("title")
    context = {"basket_list": request.session.get('basket'), 'books': books}
    context.update(get_categories())
    
    return render(request, 'treasure/index.html', context=context)

def register(request):
    if request.method == 'GET':
        context = {"basket_list": request.session.get('basket'), }
        return render(request, 'treasure/register.html', {'form': context})
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        pwd = request.POST['password']
        pwdr = request.POST['repeat-password']
        users = User.objects.all()
        flag = True
        for user in users:
            if name == user.username:
                flag = False
                message = "Registration is not successfull! Such username alredy exists"
                return render(request, 'treasure/register.html', {"basket_list": request.session.get('basket'), 'message': message})
            elif email == user.email:
                flag = False
                message = "Registration is not successfull! Such email is alredy registered"
                return render(request, 'treasure/register.html', {"basket_list": request.session.get('basket'), 'message': message})
            elif pwd != pwdr:
                flag = False
                message = "Registration is not successfull! Entered paswords do not match"
                return render(request, 'treasure/register.html', {"basket_list": request.session.get('basket'), 'message': message})
        if flag:
            if pwd == pwdr:
                min_length = 8
                if len(pwdr) < min_length:
                    message = f"Password does not meet the requirements - it must be at least {min_length} characters long."
                    return render(request, 'treasure/register.html',
                                  {"basket_list": request.session.get('basket'), 'message': message})

                # check for digit
                elif sum(c.isdigit() for c in pwdr) < 1:
                    message = "Password does not meet the requirements - it must contain at least 1 number."
                    return render(request, 'treasure/register.html',
                              {"basket_list": request.session.get('basket'), 'message': message})
                # check for uppercase letter
                elif not any(c.isupper() for c in pwdr):
                    message = "Password does not meet the requirements - it must contain at least 1 uppercase letter."
                    return render(request, 'treasure/register.html',
                                  {"basket_list": request.session.get('basket'), 'message': message})
                # check for lowercase letter
                elif not any(c.islower() for c in pwdr):
                    message = "Password does not meet the requirements - it must contain at least 1 lowercase letter."
                    return render(request, 'treasure/register.html',
                              {"basket_list": request.session.get('basket'), 'message': message})
                else:
                    securePass = make_password(pwdr)
                    new_comment = User(username=name, email=email, password=securePass, is_superuser=0, is_staff=0,
                                       is_active=1)
                    new_comment.save()
                    return redirect('index')



def logout_view(request):
    logout(request)
    return redirect('index')


def shop(request):
    show = request.GET.get('show')
    sorter = request.GET.get('sort')
    if sorter == 'title':
        books = Books.objects.all().order_by('title')
    elif sorter == 'titleDsc':
        books = Books.objects.all().order_by('-title')
    elif sorter == 'author':
        books = Books.objects.all().order_by('author')
    elif sorter == 'authorDsc':
        books = Books.objects.all().order_by('-author')
    elif sorter == 'price':
        books = Books.objects.all().order_by('price')
    elif sorter == 'priceDsc':
        books = Books.objects.all().order_by('-price')
    else:
        books = Books.objects.all()

    if show == "12":
        paginator = Paginator(books, 12)
    elif show == "10":
        paginator = Paginator(books, 10)
    elif show == "8":
        paginator = Paginator(books, 8)
    elif show == "5":
        paginator = Paginator(books, 5)
    elif show == "3":
        paginator = Paginator(books, 3)
    else:
        paginator = Paginator(books, 12)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"basket_list": request.session.get('basket'), 'books': page_obj, 'sort': sorter}
    context.update(get_categories())
    
    return render(request, 'treasure/shop-grid.html', context)

def search(request):
    query = request.GET.get('query')
    findbooks = Books.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))
    paginator = Paginator(findbooks, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"basket_list": request.session.get('basket'), 'books': page_obj}
    context.update(get_categories())
    
    return render(request, 'treasure/shop-grid.html', context=context)


def contact(request):
    context = {"basket_list": request.session.get('basket') }
    context.update(get_categories())
    
    return render(request, 'treasure/contact.html', context=context)


def order_complete(request):
    context = {"basket_list": request.session.get('basket')}
    context.update(get_categories())

    return render(request, 'treasure/order_complete.html', context=context)

def bookDetails(request, id=None):
    bookdetails = get_object_or_404(Books, title=id)
    categories = Categories.objects.all()
    comments = Comments.objects.all().order_by("-publish_date")
    rate = 0
    i = 0
    irated = 0
    for comment in comments:
        if comment.posted_id == bookdetails.id:
            if int(comment.rating) != 0:
                rate += int(comment.rating)
                irated += 1
            i += 1
    avg = 0 if i < 1 else rate/irated
    avg = round(avg, 1)

    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        pdate = timezone.now()
        rating = request.POST['star']
        if name == "" or email == "":
            message = "Please check name and email"
            context = {"basket_list": request.session.get('basket'), "details": bookdetails, "comments": comments, "categories": categories, "avgrate": avg,
                       "iter": i, "errMsg": message, "iterRated": irated}
            context.update(get_categories())
            
            return render(request, 'treasure/product-details.html', context=context)

        else:
            new_comment = Comments(name=name, email=email, comment=comment, publish_date=pdate, rating=rating, posted_id = bookdetails.id, user_id=1)
            new_comment.save()
            context = {"basket_list": request.session.get('basket'), "details":bookdetails, "comments": comments, "categories":categories, "avgrate": avg, "iter": i, "iterRated": irated}
            context.update(get_categories())
            
            return render(request, 'treasure/product-details.html', context=context)
    else:
        context = {"basket_list": request.session.get('basket'), "details": bookdetails, "comments": comments, "categories": categories, "avgrate": avg, "iter": i, "iterRated": irated}
        context.update(get_categories())
        
        return render(request, 'treasure/product-details.html', context=context)

def category(request, name=None):
    ctgry = get_object_or_404(Categories, category=name)
    books = Books.objects.filter(fk_category=ctgry)
    paginator = Paginator(books, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"basket_list": request.session.get('basket'), 'books': page_obj}
    context.update(get_categories())
    
    return render(request, 'treasure/shop-grid.html', context=context)

def cart(request):
    session_data = request.session.get('basket')
    id_set = []
    qty = []
    prices = []

    if session_data != None:
        for elem in session_data:
            id_set.append(elem['bookID'])
            qty.append(elem['qty'])

    ordered = Books.objects.filter(id__in=id_set)

    for product in ordered:
        prices.append(product.price)

    subtotal = [float(qty[i]) * float(prices[i]) for i in range(len(prices))]

    objects = zip(ordered, qty, subtotal)

    total = sum(subtotal)
    context = {"basket_list": session_data, "objects":objects, "total": total}
    context.update(get_categories())
    

templates/treasure/cart.html
{% extends "./frame.html" %}
{% load static %}
{% block content %}

		<section class="breadcrumb-section">
			<h2 class="sr-only">Site Breadcrumb</h2>
			<div class="container">
				<div class="breadcrumb-contents">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active">Cart</li>
						</ol>
					</nav>
				</div>
			</div>
		</section>
		<!-- Cart Page Start -->
		<main class="cart-page-main-block inner-page-sec-padding-bottom">
			<div class="cart_area cart-area-padding  ">
				<div class="container">
					<div class="page-section-title">
						<h1>Shopping Cart</h1>
					</div>
					<div class="row">
						<div class="col-12">
<!--							<form action="#" class="">-->
								<!-- Cart Table -->
								<div class="cart-table table-responsive mb--40">
									<table class="table">
										<!-- Head Row -->
										<thead>
											<tr>
												<th class="pro-remove"></th>
												<th class="pro-thumbnail">Image</th>
												<th class="pro-title">Product</th>
												<th class="pro-price">Price</th>
												<th class="pro-quantity">Quantity</th>
												<th class="pro-subtotal">Total</th>
											</tr>
										</thead>
										<tbody>
											<!-- Product Row -->
											{% for book, qty, sbt in objects %}
											<tr>
												<td class="pro-remove">
													<form action="{% url 'basket:remove' bookTitle=book.title %}" method="POST">{% csrf_token %}
														<input type="hidden" name="bookID" value="{{book.id}}">
														<input type="hidden" name="url_from" value="{{ request.path }}">
														<button type="submit"> <i class="far fa-trash-alt"></i></button>
													</form>

												</td>
												<td class="pro-thumbnail"><a href="#"><img
															src="{{book.image.url}}" alt="Product"></a></td>
												<td class="pro-title"><a href="{% url 'bookDetails' id=book.title %}">{{book.title}}</a></td>
												<td class="pro-price"><span>{{book.price}} ₴</span></td>
												<td class="pro-quantity">
													<span>{{qty}}</span>
<!--													<div class="pro-qty">-->
<!--														<div class="count-input-block">-->
<!--															<input type="number" class="form-control text-center" value="{{qty}}">-->
<!--														</div>-->
<!--													</div>-->
												</td>
												<td class="pro-subtotal"><span>{{sbt}} ₴</span></td>
											</tr>
											{% endfor %}

											<!-- Discount Row  -->
											<tr>
												<td colspan="6" class="actions">
													<div class="coupon-block">
														<div class="coupon-text">
															<label for="coupon_code">Coupon:</label>
															<input type="text" name="coupon_code" class="input-text"
																id="coupon_code" value="" placeholder="Coupon code">
														</div>
														<div class="coupon-btn">
															<input type="submit" class="btn btn-outlined"
																name="apply_coupon" value="Apply coupon">
														</div>
													</div>
<!--													<div class="update-block text-right">-->
<!--														<input type="submit" class="btn btn-outlined" name="update_cart"-->
<!--															value="Update cart">-->
<!--														<input type="hidden" id="_wpnonce" name="_wpnonce"-->
<!--															value="05741b501f"><input type="hidden"-->
<!--															name="_wp_http_referer" value="/petmark/cart/">-->
<!--													</div>-->
												</td>
											</tr>
										</tbody>
									</table>
								</div>
<!--							</form>-->
						</div>
					</div>
				</div>
			</div>
			<div class="cart-section-2">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-12 mb--30 mb-lg--0">
							<!-- slide Block 5 / Normal Slider -->
							<div class="cart-block-title">
								<h2>YOU MAY BE INTERESTED IN…</h2>
							</div>
							<div class="product-slider sb-slick-slider" data-slick-setting='{
							          "autoplay": true,
							          "autoplaySpeed": 8000,
							          "slidesToShow": 2
									  }' data-slick-responsive='[
                {"breakpoint":992, "settings": {"slidesToShow": 2} },
                {"breakpoint":768, "settings": {"slidesToShow": 3} },
                {"breakpoint":575, "settings": {"slidesToShow": 2} },
                {"breakpoint":480, "settings": {"slidesToShow": 1} },
                {"breakpoint":320, "settings": {"slidesToShow": 1} }
            ]'>
								<div class="single-slide">
									<div class="product-card">
										<div class="product-header">
											<span class="author">
												Lpple
											</span>
											<h3><a href="product-details.html">Revolutionize Your BOOK With These
													Easy-peasy Tips</a></h3>
										</div>
										<div class="product-card--body">
											<div class="card-image">
												<img src="{% static 'treasure/image/products/product-10.jpg' %}" alt="">
												<div class="hover-contents">
													<a href="product-details.html" class="hover-image">
														<img src="{% static 'treasure/image/products/product-1.jpg' %}" alt="">
													</a>
													<div class="hover-btns">
														<a href="cart.html" class="single-btn">
															<i class="fas fa-shopping-basket"></i>
														</a>
														<a href="wishlist.html" class="single-btn">
															<i class="fas fa-heart"></i>
														</a>
														<a href="compare.html" class="single-btn">
															<i class="fas fa-random"></i>
														</a>
														<a href="#" data-toggle="modal" data-target="#quickModal"
															class="single-btn">
															<i class="fas fa-eye"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="price-block">
												<span class="price">£51.20</span>
												<del class="price-old">£51.20</del>
												<span class="price-discount">20%</span>
											</div>
										</div>
									</div>
								</div>
								<div class="single-slide">
									<div class="product-card">
										<div class="product-header">
											<span class="author">
												Jpple
											</span>
											<h3><a href="product-details.html">Turn Your BOOK Into High Machine</a></h3>
										</div>
										<div class="product-card--body">
											<div class="card-image">
												<img src="{% static 'treasure/image/products/product-2.jpg' %}" alt="">
												<div class="hover-contents">
													<a href="product-details.html" class="hover-image">
														<img src="{% static 'treasure/image/products/product-1.jpg' %}" alt="">
													</a>
													<div class="hover-btns">
														<a href="cart.html" class="single-btn">
															<i class="fas fa-shopping-basket"></i>
														</a>
														<a href="wishlist.html" class="single-btn">
															<i class="fas fa-heart"></i>
														</a>
														<a href="compare.html" class="single-btn">
															<i class="fas fa-random"></i>
														</a>
														<a href="#" data-toggle="modal" data-target="#quickModal"
															class="single-btn">
															<i class="fas fa-eye"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="price-block">
												<span class="price">£51.20</span>
												<del class="price-old">£51.20</del>
												<span class="price-discount">20%</span>
											</div>
										</div>
									</div>
								</div>
								<div class="single-slide">
									<div class="product-card">
										<div class="product-header">
											<span class="author">
												Wpple
											</span>
											<h3><a href="product-details.html">3 Ways Create Better BOOK With</a></h3>
										</div>
										<div class="product-card--body">
											<div class="card-image">
												<img src="{% static 'treasure/image/products/product-3.jpg' %}" alt="">
												<div class="hover-contents">
													<a href="product-details.html" class="hover-image">
														<img src="{% static 'treasure/image/products/product-2.jpg' %}" alt="">
													</a>
													<div class="hover-btns">
														<a href="cart.html" class="single-btn">
															<i class="fas fa-shopping-basket"></i>
														</a>
														<a href="wishlist.html" class="single-btn">
															<i class="fas fa-heart"></i>
														</a>
														<a href="compare.html" class="single-btn">
															<i class="fas fa-random"></i>
														</a>
														<a href="#" data-toggle="modal" data-target="#quickModal"
															class="single-btn">
															<i class="fas fa-eye"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="price-block">
												<span class="price">£51.20</span>
												<del class="price-old">£51.20</del>
												<span class="price-discount">20%</span>
											</div>
										</div>
									</div>
								</div>
								<div class="single-slide">
									<div class="product-card">
										<div class="product-header">
											<span class="author">
												Epple
											</span>
											<h3><a href="product-details.html">What You Can Learn From Bill Gates</a>
											</h3>
										</div>
										<div class="product-card--body">
											<div class="card-image">
												<img src="{% static 'treasure/image/products/product-5.jpg' %}" alt="">
												<div class="hover-contents">
													<a href="product-details.html" class="hover-image">
														<img src="{% static 'treasure/image/products/product-4.jpg' %}" alt="">
													</a>
													<div class="hover-btns">
														<a href="cart.html" class="single-btn">
															<i class="fas fa-shopping-basket"></i>
														</a>
														<a href="wishlist.html" class="single-btn">
															<i class="fas fa-heart"></i>
														</a>
														<a href="compare.html" class="single-btn">
															<i class="fas fa-random"></i>
														</a>
														<a href="#" data-toggle="modal" data-target="#quickModal"
															class="single-btn">
															<i class="fas fa-eye"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="price-block">
												<span class="price">£51.20</span>
												<del class="price-old">£51.20</del>
												<span class="price-discount">20%</span>
											</div>
										</div>
									</div>
								</div>
								<div class="single-slide">
									<div class="product-card">
										<div class="product-header">
											<span class="author">
												Hpple
											</span>
											<h3><a href="product-details.html">Simple Things You To Save BOOK</a></h3>
										</div>
										<div class="product-card--body">
											<div class="card-image">
												<img src="{% static 'treasure/image/products/product-6.jpg' %}" alt="">
												<div class="hover-contents">
													<a href="product-details.html" class="hover-image">
														<img src="{% static 'treasure/image/products/product-4.jpg' %}" alt="">
													</a>
													<div class="hover-btns">
														<a href="cart.html" class="single-btn">
															<i class="fas fa-shopping-basket"></i>
														</a>
														<a href="wishlist.html" class="single-btn">
															<i class="fas fa-heart"></i>
														</a>
														<a href="compare.html" class="single-btn">
															<i class="fas fa-random"></i>
														</a>
														<a href="#" data-toggle="modal" data-target="#quickModal"
															class="single-btn">
															<i class="fas fa-eye"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="price-block">
												<span class="price">£51.20</span>
												<del class="price-old">£51.20</del>
												<span class="price-discount">20%</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- Cart Summary -->
						<div class="col-lg-6 col-12 d-flex">
							<div class="cart-summary">
								<div class="cart-summary-wrap">
									<h4><span>Cart Summary</span></h4>
									<p>Sub Total <span class="text-primary">{{total}} ₴</span></p>
									<p>Shipping Cost <span class="text-primary">$00.00</span></p>
									<h2>Grand Total <span class="text-primary">{{total}} ₴</span></h2>
								</div>
								<div class="cart-summary-button">
									<a href="{% url 'checkout' %}" class="checkout-btn c-btn btn--primary">Checkout</a>
<!--									<button class="update-btn c-btn btn-outlined">Update Cart</button>-->
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		<!-- Cart Page End -->
	</div>
{% endblock %}